/* CATEGORIES */
export const FETCH_CATEGORIES_PENDING = 'FETCH_CATEGORIES_PENDING';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';

/* GIVEN_OFFERS */
export const FETCH_GIVEN_OFFERS_PENDING = 'FETCH_GIVEN_OFFERS_PENDING';
export const FETCH_GIVEN_OFFERS_SUCCESS = 'FETCH_GIVEN_OFFERS_SUCCESS';
export const FETCH_GIVEN_OFFERS_FAILURE = 'FETCH_GIVEN_OFFERS_FAILURE';

/* DETAILS */
export const FETCH_DETAILS_PENDING = 'FETCH_DETAILS_PENDING';
export const FETCH_DETAILS_SUCCESS = 'FETCH_DETAILS_SUCCESS';
export const FETCH_DETAILS_FAILURE = 'FETCH_DETAILS_FAILURE';

/* PRODUCTS */
export const FETCH_PRODUCTS_PENDING = 'FETCH_PRODUCTS_PENDING';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

/* RECEIVED_OFFERS */
export const FETCH_RECEIVED_OFFERS_PENDING = 'FETCH_RECEIVED_OFFERS_PENDING';
export const FETCH_RECEIVED_OFFERS_SUCCESS = 'FETCH_RECEIVED_OFFERS_SUCCESS';
export const FETCH_RECEIVED_OFFERS_FAILURE = 'FETCH_RECEIVED_OFFERS_FAILURE';

/* SIGNIN */
export const FETCH_SIGNIN_PENDING = 'FETCH_SIGNIN_PENDING';
export const FETCH_SIGNIN_SUCCESS = 'FETCH_SIGNIN_SUCCESS';
export const FETCH_SIGNIN_FAILURE = 'FETCH_SIGNIN_FAILURE';
export const SIGNIN_CLEAR = 'SIGNIN_CLEAR';

/* SIGNUP */
export const FETCH_SIGNUP_PENDING = 'FETCH_SIGNUP_PENDING';
export const FETCH_SIGNUP_SUCCESS = 'FETCH_SIGNUP_SUCCESS';
export const FETCH_SIGNUP_FAILURE = 'FETCH_SIGNUP_FAILURE';
export const SIGNUP_CLEAR = 'SIGNUP_CLEAR';

/* PURCHASE */
export const FETCH_PURCHASE_PENDING = 'FETCH_PURCHASE_PENDING';
export const FETCH_PURCHASE_SUCCESS = 'FETCH_PURCHASE_SUCCESS';
export const FETCH_PURCHASE_FAILURE = 'FETCH_PURCHASE_FAILURE';

/* SEND_OFFER */
export const FETCH_SEND_OFFER_PENDING = 'FETCH_SEND_OFFER_PENDING ';
export const FETCH_SEND_OFFER_SUCCESS = 'FETCH_SEND_OFFER_SUCCESS';
export const FETCH_SEND_OFFER_FAILURE = 'FETCH_SEND_OFFER_FAILURE';

/* ACCEPT_OFFER */
export const FETCH_ACCEPT_OFFER_PENDING = 'FETCH_ACCEPT_OFFER_PENDING ';
export const FETCH_ACCEPT_OFFER_SUCCESS = 'FETCH_ACCEPT_OFFER_SUCCESS';
export const FETCH_ACCEPT_OFFER_FAILURE = 'FETCH_ACCEPT_OFFER_FAILURE';

/* BRANDS */
export const FETCH_BRAND_PENDING = 'FETCH_BRAND_PENDING ';
export const FETCH_BRAND_SUCCESS = 'FETCH_BRAND_SUCCESS';
export const FETCH_BRAND_FAILURE = 'FETCH_BRAND_FAILURE';

/* COLORS */
export const FETCH_COLOR_PENDING = 'FETCH_COLOR_PENDING ';
export const FETCH_COLOR_SUCCESS = 'FETCH_COLOR_SUCCESS';
export const FETCH_COLOR_FAILURE = 'FETCH_COLOR_FAILURE';

/* STATUS */
export const FETCH_STATUS_PENDING = 'FETCH_STATUS_PENDING ';
export const FETCH_STATUS_SUCCESS = 'FETCH_STATUS_SUCCESS';
export const FETCH_STATUS_FAILURE = 'FETCH_STATUS_FAILURE';

/* CANCEL */
export const FETCH_CANCEL_PENDING = 'FETCH_CANCEL_PENDING ';
export const FETCH_CANCEL_SUCCESS = 'FETCH_CANCEL_SUCCESS';
export const FETCH_CANCEL_FAILURE = 'FETCH_CANCEL_FAILURE';

/* REJECT */
export const FETCH_REJECT_PENDING = 'FETCH_REJECT_PENDING ';
export const FETCH_REJECT_SUCCESS = 'FETCH_REJECT_SUCCESS';
export const FETCH_REJECT_FAILURE = 'FETCH_REJECT_FAILURE';

/* IMAGE_UPLOAD */
export const FETCH_IMAGE_UPLOAD_PENDING = 'FETCH_IMAGE_UPLOAD_PENDING ';
export const FETCH_IMAGE_UPLOAD_SUCCESS = 'FETCH_IMAGE_UPLOAD_SUCCESS';
export const FETCH_IMAGE_UPLOAD_FAILURE = 'FETCH_IMAGE_UPLOAD_FAILURE';
