/* CATEGORIES */
export const FETCH_CATEGORIES_PENDING = 'FETCH_CATEGORIES_PENDING';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';

/* GIVEN_OFFERS */
export const FETCH_GIVEN_OFFERS_PENDING = 'FETCH_GIVEN_OFFERS_PENDING';
export const FETCH_GIVEN_OFFERS_SUCCESS = 'FETCH_GIVEN_OFFERS_SUCCESS';
export const FETCH_GIVEN_OFFERS_FAILURE = 'FETCH_GIVEN_OFFERS_FAILURE';

/* DETAILS */
export const FETCH_DETAILS_PENDING = 'FETCH_DETAILS_PENDING';
export const FETCH_DETAILS_SUCCESS = 'FETCH_DETAILS_SUCCESS';
export const FETCH_DETAILS_FAILURE = 'FETCH_DETAILS_FAILURE';

/* PRODUCTS */
export const FETCH_PRODUCTS_PENDING = 'FETCH_PRODUCTS_PENDING';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

/* RECEIVED_OFFERS */
export const FETCH_RECEIVED_OFFERS_PENDING = 'FETCH_RECEIVED_OFFERS_PENDING';
export const FETCH_RECEIVED_OFFERS_SUCCESS = 'FETCH_RECEIVED_OFFERS_SUCCESS';
export const FETCH_RECEIVED_OFFERS_FAILURE = 'FETCH_RECEIVED_OFFERS_FAILURE';

/* SIGNIN */
export const FETCH_SIGNIN_PENDING = 'FETCH_SIGNIN_PENDING';
export const FETCH_SIGNIN_SUCCESS = 'FETCH_SIGNIN_SUCCESS';
export const FETCH_SIGNIN_FAILURE = 'FETCH_SIGNIN_FAILURE';

/* SIGNUP */
export const FETCH_SIGNUP_PENDING = 'FETCH_SIGNUP_PENDING';
export const FETCH_SIGNUP_SUCCESS = 'FETCH_SIGNUP_SUCCESS';
export const FETCH_SIGNUP_FAILURE = 'FETCH_SIGNUP_FAILURE';

/* PURCHASE */
export const FETCH_PURCHASE_PENDING = 'FETCH_PURCHASE_PENDING';
export const FETCH_PURCHASE_SUCCESS = 'FETCH_PURCHASE_SUCCESS';
export const FETCH_PURCHASE_FAILURE = 'FETCH_PURCHASE_FAILURE';
